global _start

section .text
_start:
    mov rax, 12;
    mov rdi, 0;
    syscall;

    mov [tape], rax;
    mov [pointer], rax;

    add rax, 30000;
    add rdi, rax;
    mov rax, 12;

    inc qword [pointer];
    mov rax, [pointer];
    add byte [rax], 8;
    dec qword [pointer];
    mov rax, [pointer];
    add byte [rax], 9;
    inc qword [pointer];
    mov rax, [pointer];
    dec byte [rax];
    dec qword [pointer];
    mov rax, 1;
    mov rdi, 1;
    mov rsi, [pointer];
    mov rdx, 1;
    syscall;
    inc qword [pointer];
    mov rax, [pointer];
    add byte [rax], 4;
    dec qword [pointer];
    mov rax, [pointer];
    add byte [rax], 7;
    inc qword [pointer];
    mov rax, [pointer];
    dec byte [rax];
    dec qword [pointer];
    mov rax, [pointer];
    inc byte [rax];
    mov rax, 1;
    mov rdi, 1;
    mov rsi, [pointer];
    mov rdx, 1;
    syscall;
    mov rax, [pointer];
    add byte [rax], 7;
    mov rax, 1;
    mov rdi, 1;
    mov rsi, [pointer];
    mov rdx, 1;
    syscall;
    mov rax, 1;
    mov rdi, 1;
    mov rsi, [pointer];
    mov rdx, 1;
    syscall;
    mov rax, [pointer];
    add byte [rax], 3;
    mov rax, 1;
    mov rdi, 1;
    mov rsi, [pointer];
    mov rdx, 1;
    syscall;
    add qword [pointer], 2;
    mov rax, [pointer];
    add byte [rax], 6;
    dec qword [pointer];
    mov rax, [pointer];
    add byte [rax], 7;
    inc qword [pointer];
    mov rax, [pointer];
    dec byte [rax];
    dec qword [pointer];
    mov rax, [pointer];
    add byte [rax], 2;
    mov rax, 1;
    mov rdi, 1;
    mov rsi, [pointer];
    mov rdx, 1;
    syscall;
    mov rax, [pointer];
    dec byte [rax];
    mov rax, [pointer];
    dec byte [rax];
    mov rax, [pointer];
    dec byte [rax];
    mov rax, [pointer];
    dec byte [rax];
    mov rax, [pointer];
    dec byte [rax];
    mov rax, [pointer];
    dec byte [rax];
    mov rax, [pointer];
    dec byte [rax];
    mov rax, [pointer];
    dec byte [rax];
    mov rax, [pointer];
    dec byte [rax];
    mov rax, [pointer];
    dec byte [rax];
    mov rax, [pointer];
    dec byte [rax];
    mov rax, [pointer];
    dec byte [rax];
    mov rax, 1;
    mov rdi, 1;
    mov rsi, [pointer];
    mov rdx, 1;
    syscall;
    inc qword [pointer];
    mov rax, [pointer];
    add byte [rax], 6;
    dec qword [pointer];
    mov rax, [pointer];
    add byte [rax], 9;
    inc qword [pointer];
    mov rax, [pointer];
    dec byte [rax];
    dec qword [pointer];
    mov rax, [pointer];
    inc byte [rax];
    mov rax, 1;
    mov rdi, 1;
    mov rsi, [pointer];
    mov rdx, 1;
    syscall;
    dec qword [pointer];
    mov rax, 1;
    mov rdi, 1;
    mov rsi, [pointer];
    mov rdx, 1;
    syscall;
    mov rax, [pointer];
    add byte [rax], 3;
    mov rax, 1;
    mov rdi, 1;
    mov rsi, [pointer];
    mov rdx, 1;
    syscall;
    mov rax, [pointer];
    dec byte [rax];
    mov rax, [pointer];
    dec byte [rax];
    mov rax, [pointer];
    dec byte [rax];
    mov rax, [pointer];
    dec byte [rax];
    mov rax, [pointer];
    dec byte [rax];
    mov rax, [pointer];
    dec byte [rax];
    mov rax, 1;
    mov rdi, 1;
    mov rsi, [pointer];
    mov rdx, 1;
    syscall;
    mov rax, [pointer];
    dec byte [rax];
    mov rax, [pointer];
    dec byte [rax];
    mov rax, [pointer];
    dec byte [rax];
    mov rax, [pointer];
    dec byte [rax];
    mov rax, [pointer];
    dec byte [rax];
    mov rax, [pointer];
    dec byte [rax];
    mov rax, [pointer];
    dec byte [rax];
    mov rax, [pointer];
    dec byte [rax];
    mov rax, 1;
    mov rdi, 1;
    mov rsi, [pointer];
    mov rdx, 1;
    syscall;
    add qword [pointer], 3;
    mov rax, [pointer];
    add byte [rax], 4;
    dec qword [pointer];
    mov rax, [pointer];
    add byte [rax], 8;
    inc qword [pointer];
    mov rax, [pointer];
    dec byte [rax];
    dec qword [pointer];
    mov rax, [pointer];
    inc byte [rax];
    mov rax, 1;
    mov rdi, 1;
    mov rsi, [pointer];
    mov rdx, 1;
    syscall;

    mov rax, 12;
    mov rdi, tape;
    syscall;

    mov rax, 60;
    xor rdi, rdi;
    syscall;

section .data
tape: dq 0;
pointer: dq 0;
